version: 0.0
os: linux
files:
   - source: /
     destination: /var/development
permissions:
   - object: /var/development
     pattern: "**"
     owner: apache
     group: apache
     mode: 755
     type:
       - file