template: Hello, %s!
defaultName: Stranger
myServiceDb:
    driverClass: org.postgresql.Driver
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost/postgres
    properties:
        charSet: UTF-8
        validationQuery: "SELECT 1"
        validationQueryTimeout: 5s
        initialize: 8
        minSize: 8
        maxSize: 150
        checkConnectionWhileIdle: true
        evictionInterval: 10s
        minIdleTime: 1 minute
server:
  applicationConnectors:
  - type: http
    port: 8082
    reuseAddress: true
    idleTimeout: 75 seconds # Must be longer than ELB timeout (defaults to 60 seconds).
  adminConnectors:
  - type: http
    port: 8083